### ISSUE TITLE
[NPC] ID 16553 - Корчмарь Челлана <Хозяйка таверны

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#103]
**Ссылки и комментарии:**

http://ru.wowhead.com/npc=16553

**Что работает не так?**

Визуальный баг. Вместо названия диалога, призванного задавать вопрос из серии "Что ты такое", удвоенное написание "Позволь мне взглянуть на ваши товары"
![wowscrnshot_020318_124647](https://user-images.githubusercontent.com/29457913/35766020-2348e096-08e9-11e8-8792-7abc20e25898.jpg)

**Как должно работать?**

Вместо первого "Позволь мне взглянуть на ваши товары" должно быть "Что будет, если я остановлюсь здесь?" (или что-то в этом роде)

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

**Comment by Kodekc** [comment]
Поправлено диалоговое меню
