### ISSUE TITLE
 [Заклинание] ID 2484 - Тотем оков земли (дреней)

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#112]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=2484
http://ru.wowhead.com/spell=2484#screenshots:id=138013

**Что работает не так?**

Тотем дренея не имеет модельки - отображается клетчатый кубик
![wowscrnshot_020518_154858](https://user-images.githubusercontent.com/29457913/35805284-a8cc5e26-0a94-11e8-8c75-e3b29834dc4e.jpg)

**Как должно работать?**

Тотем дожен иметь модельку

**Шаги для воспроизведения ошибки:**

1. Ставим тотем

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

**Comment by ForesterDev** [comment]
Исправлено
