### ISSUE TITLE
[Заклинание] ID 403 - Молния

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#114]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=403
http://ru.wowhead.com/maelstrom

**Что работает не так?**

Не создает Энергию водоворота

**Как должно работать?**

При использование создает 8 ед. Энергии водоворота

**Шаги для воспроизведения ошибки:**

1. Апаем 10+ лвл
2. Выбираем спек Стихии (Элем)
3. Бьем любую цель

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

**Comment by ForesterDev** [comment]
Исправлено
