### ISSUE TITLE
[NPC] ID 50306 - Каду <Интендант Экзодара>

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#115]
**Ссылки и комментарии:**

http://ru.wowhead.com/npc=50306

**Что работает не так?**

Невозможно поговорить с интендантом, не открывается набор товаров.

**Как должно работать?**

Должен продавать предметы за репутацию.

**Шаги для воспроизведения ошибки:**

1. Идем в Экзодар
2. Находим НПЦ
3. Кликаем правой кнопкой мыши

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

**Comment by Kodekc** [comment]
Updated Kadu (npc vendor)
