### ISSUE TITLE
 [NPC] ID 37674 - Милая продавщица <Королевская химическая компания>

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#117]
**Ссылки и комментарии:**

http://ru.wowhead.com/npc=37674

**Что работает не так?**

Неверный набор товаров. бОльшей части товаров нет (в частности маунт, петы, улучшения для фамильных вещей, игрушки, крем для мелкошустра). Набор товаров времен 3.3.5 

**Как должно работать?**

Должен быть совсем другой набор продаваемых вещей.

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

**Comment by Kodekc** [comment]
Updated Lovely Merchant <Crown Chemical Co.> (npc vendor)
