### ISSUE TITLE
[Задание] ID 8483 - Дворфийский шпион

### ISSUE THREAD

**Issue by Sinegosa** [VirginTeam/LegionCore#12]
**Описание:**

кв [[The Dwarven Spy]](http://www.wowhead.com/quest=8483/the-dwarven-spy) невозможо выполнить, так как не работает диалог у нпс Геолог Страж Наковальни

**Что работает не так?**

У нпс [Геолог Страж Наковальни](http://ru.wowhead.com/npc=15420) не работает диалог (не кликабельный), соответственно задание [[The Dwarven Spy]](http://www.wowhead.com/quest=8483/the-dwarven-spy) выполнить невозможно.

https://cdn.discordapp.com/attachments/405749645160218624/405764227463380992/unknown.png

**Как должно работать?**

Диалог должен быть рабочим, он запускает ивент. НПС поднимается на второй этаж, рассказывает историю и затем начинает бить игрока. После убийства с него падает [голова ](http://ru.wowhead.com/item=20764)необходимая для сдачи задания.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Sinegosa** [comment]
актуально для тринити

**Comment by Kodekc** [comment]
Updated Prospector Anvilward (gossip menu)
