### ISSUE TITLE
 [NPC] ID 17554 - Лаандо <Укротитель гиппогрифов>

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#120]
**Ссылки и комментарии:**

http://ru.wowhead.com/npc=17554

**Что работает не так?**

Не дает доступ к полетам.

**Как должно работать?**

Ожидаемый результат — воспользоваться перелетом :)

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

**Comment by Kodekc** [comment]
Исправлено
