### ISSUE TITLE
[Игровая механика] - Регистрация на прохождение случайного подземелья

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#122]
**Что работает не так?**

Можно регнуть любое подземелье легиона и часть 90+
![wowscrnshot_020918_134745](https://user-images.githubusercontent.com/29457913/36024270-ad01b844-0da8-11e8-97e1-510e0a22444e.jpg)
![wowscrnshot_020918_134753](https://user-images.githubusercontent.com/29457913/36024271-ad3af76c-0da8-11e8-966d-739c4e9ac48c.jpg)
![wowscrnshot_020918_134756](https://user-images.githubusercontent.com/29457913/36024273-ad71ba7c-0da8-11e8-8c21-5695be092de9.jpg)

**Как должно работать?**

Подземелья должны открываться постепенно при достижении соответствующего лвл персонажа.

**Шаги для воспроизведения ошибки:**

1. Получить 15+ лвл
2. Открыть рег
3. Регнуть любое пп по желанию

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

**Comment by ForesterDev** [comment]
Исправлено
