### ISSUE TITLE
[NPC] ID 6736 - Кельдамир <Хозяин таверны>

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#124]
**Ссылки и комментарии:**

http://ru.wowhead.com/npc=6736

**Что работает не так?**

Невозможно закрепить Камень возвращения и купить воду/еду - нет диалогов.

**Как должно работать?**

Ожидаемый результат - закрепить камень и купить воду/еду.

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

**Comment by Kodekc** [comment]
Исправлено.
