### ISSUE TITLE
[NPC] ID 36697 - Заклинательница шипов из племени Дыбогривов

### ISSUE THREAD

**Issue by Anafobia** [VirginTeam/LegionCore#132]
**Ссылки и комментарии:**

http://ru.wowhead.com/npc=36697

**Что работает не так?**

Отсутствует лут.

**Как должно работать?**

После убийства должен быть лут.

**Шаги для воспроизведения ошибки:**

1. Убиваем заклинательницу.
2. Пытаемся залутать.

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
- Добавлена недостающая информация о добыче с существа
- Добавлена добыча денег

**Comment by gmOverfire** [comment]
#262
