### ISSUE TITLE
[Задание] ID 27027 - Стихийный удар (таурен)

### ISSUE THREAD

**Issue by Anafobia** [VirginTeam/LegionCore#135]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=27027

**Что работает не так?**

Устаревшее задание, не должно выдаваться вообще, т.к. отсутствует сама способность "стихийного удара". 

**Как должно работать?**

По идее в легионе убрали после патча 7.1.3.

**Шаги для воспроизведения ошибки:**

1. Берем квест.
2. Ищем спелл.

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Senatyan** [comment]
Добавлено в обновлении 4.0.3.13277
Даже в начале клизмы его убрали

**Comment by Anafobia** [comment]
Может и раньше, в 7.1.3. его уже нет.

**Comment by Senatyan** [comment]
Не будет его, если в клизме убрали

**Comment by Ewropa** [comment]
Все классовые задания, по практике навыков были убраны из игры с выходом Легиона

**Comment by Kodekc** [comment]
Удалено
