### ISSUE TITLE
[Задание] ID 24215 - Обряды Ветров

### ISSUE THREAD

**Issue by Anafobia** [VirginTeam/LegionCore#136]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=24215

**Что работает не так?**

Выбивает из формы птицы. В итоге игрок разбивается.

**Как должно работать?**

https://www.youtube.com/watch?v=A1KBmCw4Hjk&feature=youtu.be (видео с офы 7.0.1)

**Шаги для воспроизведения ошибки:**

1. Берем квест у Дайми Резкий Ветер.
2. Выпиваем 	Вода провидения.
3. В процессе полета сбрасывается форма птицы.

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
После включения поиск пути и перехода на версию 7.3.5, заработало само собой :)
