### ISSUE TITLE
[Задание] ID 24440 - Очищение колодца Заиндевевшего Копыта

### ISSUE THREAD

**Issue by Anafobia** [VirginTeam/LegionCore#137]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=754

**Что работает не так?**

Автоматически сдается.

**Как должно работать?**

Добежать до колодца координаты 53.7 66.3 , заюзать квестовый итем. 
https://www.youtube.com/watch?v=lAwLQ7DOZ5E (версия прохождения дренор 6.2.3.) на вовхеде задание помечено устаревшим.

**Шаги для воспроизведения ошибки:**

1. Берем квест Мулл Громовой Рог.
2. Сдаем квест Мулл Громовой Рог.

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Ewropa** [comment]
ссылка на задание не правильная, вот действующее задание http://ru.wowhead.com/quest=24440

**Comment by Ewropa** [comment]
https://github.com/VirginTeam/LegionCore/issues/196
