### ISSUE TITLE
[Задание] ID 764 - Торговая Компания 

### ISSUE THREAD

**Issue by Anafobia** [VirginTeam/LegionCore#138]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=764

**Что работает не так?**

http://ru.wowhead.com/quest=764 - старый квест. должен быть недоступен. (заменен вторым, новым)

**Как должно работать?**

Должен быть только этот квест http://ru.wowhead.com/quest=26179

**Шаги для воспроизведения ошибки:**

1. Подходим к http://ru.wowhead.com/npc=2988.
2. Берем http://ru.wowhead.com/quest=764

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/139
