### ISSUE TITLE
[NPC] ID 4156 - Астайя <Учительница рыбной ловли>

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#146]
**Ссылки и комментарии:**

http://ru.wowhead.com/npc=4156

**Что работает не так?**

1) Не обучает Рыбной ловле. 
2) Дает рыболовный дейлик без наличия профы.

**Как должно работать?**

1) Обучает рыбной ловле
2) Дейлики даются при достижении 10 лвл и наличии профессии Рыболовное дело (1)

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

**Comment by Kodekc** [comment]
С обновлением, должно было поправится, перепроверьте

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/151
