### ISSUE TITLE
[Игровая механика] - Дерево на леопарде

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#147]
**Что работает не так?**

![wowscrnshot_021218_194132](https://user-images.githubusercontent.com/29457913/36108389-3193cf0e-1036-11e8-8333-c7341e072cc8.jpg)
 
Гуляет по Террасе ремесленников. Один в своем роде)

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

**Comment by Kodekc** [comment]
Исправлено
