### ISSUE TITLE
[NPC] ID 4210 - Элегорн <Учитель кулинарии>

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#148]
**Ссылки и комментарии:**

http://ru.wowhead.com/npc=4210

Перечень квестов:
http://ru.wowhead.com/quest=29316
http://ru.wowhead.com/quest=29314
http://ru.wowhead.com/quest=29318
http://ru.wowhead.com/quest=29313
http://ru.wowhead.com/quest=29357

**Что работает не так?**

1) Не обучает профессии Кулинарное дело: при нажатии соответствующего диалога ничего не происходит.
2) Дает все кулинарные дейлики разом при отсутствии профы.

**Как должно работать?**

1) Должен обучать профессии Кулинарное дело
2) Должен давать 1 дейлик в день при наличии профессии Кулинарное дело (1)

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

**Comment by Kodekc** [comment]
**Теперь работают правильно:**

Повар Гильм <Учитель кулинарии> (http://ru.wowhead.com/npc=1355)
Томас <Учитель кулинарии> (http://ru.wowhead.com/npc=1430)
Гремлок Пилзнор <Учитель кулинарии> (http://ru.wowhead.com/npc=1699)
Кристал Боумен <Учительница кулинарии> (http://ru.wowhead.com/npc=3087)
Элегорн <Учитель кулинарии> (http://ru.wowhead.com/npc=4210)
Мумман <Учительница кулинарии> (http://ru.wowhead.com/npc=16719)
Филдинг Честерхилл <Учитель кулинарии> (http://ru.wowhead.com/npc=50567)

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/151

**Comment by Kodekc** [comment]
Исправлена выдача ежедневных заданий
