### ISSUE TITLE
[Задание] ID 9133- Полет в Луносвет

### ISSUE THREAD

**Issue by Sinegosa** [VirginTeam/LegionCore#15]
**Описание:**

кв [[Fly to Silvermoon City]](http://www.wowhead.com/quest=9133/fly-to-silvermoon-city) не отображает на карте где сдавать

**Что работает не так?**

Карта не отображает где сдавать задание [[Fly to Silvermoon City]](http://www.wowhead.com/quest=9133/fly-to-silvermoon-city) 

**Как должно работать?**

Карта должна отображать где сдавать кв в Луносвете.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/63
