### ISSUE TITLE
[задание] ID 24492 - Пакуйте вещи

### ISSUE THREAD

**Issue by Anafobia** [VirginTeam/LegionCore#159]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=24492

**Что работает не так?**

Нет возможно заюзать и собрать квестовые итемы:
http://ru.wowhead.com/item=49756
http://ru.wowhead.com/item=49755
http://ru.wowhead.com/item=49754

**Как должно работать?**

Должно собираться. 

**Шаги для воспроизведения ошибки:**

1. Берем квест
2. Идем в Старую наковальню.
3. Смотрим на светящиеся квестовые итемы и пробуем собрать.

**Текущее обновление ядра:**

14.02.2018 Test Build - Trinity

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Anafobia** [comment]
+ по итогу садит на вертолет и увозит к сдаче квеста. Т.к. тунель завален камнями.

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/67
