### ISSUE TITLE
[Группа NPC] - Полное отсутствие лута

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#161]
**Что работает не так?**

С проверенных мобов полностью отсутствует любой лут (в т.ч. и квестовые предметы).
Перечень:

1. http://ru.wowhead.com/npc=2189
2. http://ru.wowhead.com/npc=32935
3. http://ru.wowhead.com/npc=33022
4. http://ru.wowhead.com/npc=33311
5. http://ru.wowhead.com/npc=33009
6. http://ru.wowhead.com/npc=32890

Возможно, все мобы в зоне Темные Берега без лута. Дальше по карте еще не заходила.

**Текущее обновление ядра:**

14.02.2018 Test Build - Trinity

**Comment by gmOverfire** [comment]
#262
