### ISSUE TITLE
[Заклинание] ID 183998 - Свет мученика

### ISSUE THREAD

**Issue by Anafobia** [VirginTeam/LegionCore#163]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=183998

**Что работает не так?**

Свет мученика восстанавливает хп цели без урона для игрока.

**Как должно работать?**

Свет мученика восполняет здоровье цели и наносит паладину урон в объеме 50% от исцеления.
т.е. восполняем цели 1000 ед здоровья, получаем урон 500 ед.

**Шаги для воспроизведения ошибки:**

1. паладин 63 уровня.
2. Находим дружественную цель ( у меня стражник).
3. Используем на нем свет мученика, восстанавливаем цели хп без получения урона.

**Текущее обновление ядра:**

14.02.2018 Test Build - Trinity

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
