### ISSUE TITLE
[Заклинание] ID 54149 - Прилив света

### ISSUE THREAD

**Issue by Anafobia** [VirginTeam/LegionCore#164]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=54149

**Что работает не так?**

Срабатывает от любой хилящей способности. Даже от Освящения (http://ru.wowhead.com/spell=26573).

На офе не от чего не захотел сработать. Там проверяла на паладине 92 лвл.

**Как должно работать?**

Срабатывает от критического урона/отхила способностей.

**Шаги для воспроизведения ошибки:**

1. Хилим любой способностью. Получаем ауру http://ru.wowhead.com/spell=54149
2. Используем Освящение. Получаем ауру http://ru.wowhead.com/spell=54149

**Текущее обновление ядра:**

14.02.2018 Test Build - Trinity

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
