### ISSUE TITLE
[Игровая механика] - Дубликаты заклинаний на панель

### ISSUE THREAD

**Issue by Sinegosa** [VirginTeam/LegionCore#17]
**Что работает не так?**

Если при апе уровня персонаж должен изучить новое заклинание, он получает две копии на панель. В спелбуке изучается нормально.
Проблема общая.

https://cdn.discordapp.com/attachments/405749645160218624/405772154047561735/unknown.png

**Как должно работать?**

Должна появляться только 1 иконка.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by gmOverfire** [comment]
upd

**Comment by Sinegosa** [comment]
актуально на тринити

**Comment by Kodekc** [comment]
Есть какая-то закономерность? К примеру, только на 5 уровне персонаж получает такие заклинания-дубликаты или он получает их всегда с какого-то определённого уровня или вовсе с момента старта игры.

**Comment by ForesterDev** [comment]
Такое происходит только до 10 уровня

**Comment by ForesterDev** [comment]
Исправлено
