### ISSUE TITLE
[Заклинание] ID 85256 - Вердикт храмовника

### ISSUE THREAD

**Issue by Anafobia** [VirginTeam/LegionCore#170]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=85256

**Что работает не так?**

Не наносит урон.

**Как должно работать?**

Должно наносить урон.

**Шаги для воспроизведения ошибки:**

1. накапливаем силу света.
2. Используем вердикт храмовика по цели.

**Текущее обновление ядра:**

14.02.2018 Test Build - Trinity

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
