### ISSUE TITLE
Склонение имени персонжана

### ISSUE THREAD

**Issue by WarFoll2** [VirginTeam/LegionCore#176]
**Описание проблемы:**
Склонение имени персонажа
**Что работает не так?**
Склонение имени персонажа происходит даже тогда, когда ваш персонаж выше первого уровня.
Как должно работать?
Склонение имени персонажа должно быть только при первом входе в игру. (Для имён на Русском Языке)
**Шаги для воспроизведения ошибки:**
1.Создать персожана
2. Прокачать хотя бы один уровень
3. Перезайти в игру.
4. Увидеть снова склонение имени персонажа.
**Текущее обновление ядра:**
14.02.2018 Test Build - Trinity

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/61
