### ISSUE TITLE
[Quest] id 24623 - Спасение детенышей

### ISSUE THREAD

**Issue by gmOverfire** [VirginTeam/LegionCore#180]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=24623
http://ru.wowhead.com/npc=39157
http://ru.wowhead.com/item=52283
http://ru.wowhead.com/spell=70874

**Что работает не так?**

При использовании квеститема рядом с нужным нпц ничего не происходит.

**Как должно работать?**

https://youtu.be/PqNINbDJk5o

**Текущее обновление ядра:**

19.02.2018

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Исправлено. Будет применено в ближайшем обновлении
