### ISSUE TITLE
Задание  Id 24215

### ISSUE THREAD

**Issue by Sigric** [VirginTeam/LegionCore#195]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=24215

**Что работает не так?**
 После превращение в ворона  отлетает метров 10, превращается обратно  в тарена и разбивается

**Как должно работать?**

долететь, и сдать квест

**Шаги для воспроизведения ошибки:**

1. Взять квест 
2. долететь до  деревни "кровавая копыто"
3. сдать квест

**Текущее обновление ядра:**
 24.02.2018

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/136
