### ISSUE TITLE
[Задание] ID 3060 - Лунный огонь

### ISSUE THREAD

**Issue by Sigric** [VirginTeam/LegionCore#198]
**Ссылки и комментарии:**
http://ru.wowhead.com/npc=3060
http://ru.wowhead.com/quest=27067
https://www.youtube.com/watch?v=2l739v5Voks&feature=youtu.be

**Что работает не так?**
после применение "лунный огонь" на манекене   не засчитывается  задание

**Как должно работать?**
кастуем лунный огонь на манекене  и завещаем задание  

**Шаги для воспроизведения ошибки:**

1. дается квест
2. бьем манекена 
3. сдаем квест и получаем награду

**Текущее обновление ядра:**
24.02.2018        13.27 trin.core  
Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Удалил задание из игры, его нельзя взять, это задание устаревшее
