### ISSUE TITLE
[NPC] ID 15297/15296 - Чародей Хелион и Чародей Итанас

### ISSUE THREAD

**Issue by Sinegosa** [VirginTeam/LegionCore#2]
**Описание:**

Задания - дубликаты

**Что работает не так?**

Задания [[The Shrine of Dath'Remar](http://www.wowhead.com/quest=8345/the-shrine-of-dathremar)],  [[A Fistful of Slivers]](http://www.wowhead.com/quest=8336/a-fistful-of-slivers) и [[Thirst Unending]](http://www.wowhead.com/quest=8346/thirst-unending) сразу можно взять по 2 шт каждого.

**Как должно работать?**

Каждое задание из перечисленных должно быть одно, без дубликатов

**Шаги для воспроизведения ошибки:**

1. Подходим к нпс
2. Видим сразу 2 одинаковых квеста
3. Берем один, потом берем второй. По выполнении можем сдать оба.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Kodekc** [comment]
Updated Arcanist Ithanas and Arcanist Helion (queststarter/questender).
