### ISSUE TITLE
[Quest] ID 24492 - Пакуйте вещи

### ISSUE THREAD

**Issue by Anineta** [VirginTeam/LegionCore#201]
http://ru.wowhead.com/quest=24492

**Что работает не так?**

Невозможно поднять предметы, которые нужны по заданию. Они подсвечиваются и отображаются на карте (как и должно быть), но взять их нельзя, они не активны. 
[http://ru.wowhead.com/item=49754](Бутыль пива Холодной долины)
[http://ru.wowhead.com/item=49755](Рваный плащ из волчьей шкуры)
[http://ru.wowhead.com/item=49756](Останки кабанины)

**Как должно работать?**

После того как берем квест, просто собираем кв итемы и сдаем квест.

**Шаги для воспроизведения ошибки:**

1. Берем квест
2. Бежим в место, где находятся предметы и пытаемся всё собрать
3. Понимаем что всё тщетно.

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/67
