### ISSUE TITLE
[NPC] ID 3009 - Бена Заиндевевшее Копыто <Учительница алхимии>

### ISSUE THREAD

**Issue by Sigric** [VirginTeam/LegionCore#222]
**Ссылки и комментарии:**
http://ru.wowhead.com/npc=3009
Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 

**Что работает не так?**
нет возможности обучится Алхимией 
Фактический результат — тот, который вы наблюдаете 

**Как должно работать?**
открыть окно с выбором уровни обучение алхимией 
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Текущее обновление ядра:**
triniryCore  14.52 (v7.3.5)
Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/LegionCore/issues/151
