### ISSUE TITLE
[Заклинание] ID 126892 - Духовное путешествие 

### ISSUE THREAD

**Issue by Anineta** [VirginTeam/LegionCore#229]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=126892

**Что работает не так?**

В описании написано "Чтобы вернуться обратно, используйте "Духовное путешествие" еще раз."
Если использовать еще раз, то опять телепортирует на Пик Безмятежности.

**Как должно работать?**

Юзаем "Духовное путешестие" и появляемся в Пике Безмятежности. Юзаем еще раз и возвращаемся туда, где были изначально.

**Шаги для воспроизведения ошибки:**

1. Получить 14 уровень 
2. Попробовать использовать "Духовное путешествие"
3. Разочароваться потому что придется опять бежать пешком в Лок Модан, ведь теперь ты в Пандарии и кроме как камнем отсюда никак не выбраться. 

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
