### ISSUE TITLE
[Заклинание] ID 16095 - Вывести из строя

### ISSUE THREAD

**Issue by Anineta** [VirginTeam/LegionCore#234]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=116095

Вы замедляете противника, снижая скорость его передвижения на 50% на 15 sec. Время действия эффекта будет обновлено, если вы нанесете удар в ближнем бою. Если применить способность к цели, которая уже замедлена, то вместо этого она на 8 sec. будет обездвижена.

**Что работает не так?**

При повторном использовании не обездвиживает цель. 

**Как должно работать?**

Это важно: для срабатывания обездвиживания цель не обязательно должна быть замедленна Выведением из строя! Эффект "пришпиливания" сработает, если цель замедленна Хмельной дымкой, ядом, контузией, подрезанием сухожилий, чем угодно. (с) Вовхед

**Шаги для воспроизведения ошибки:**

1. Качаем монаха до 16 лвл и пытаемся использовать скилл "Вывести из строя"
2. После использования цель замедляется, поэтому мы используем "Вывести из строя еще раз"
3. Ничего не происходит, цель всё так же движется, хоть и скрость передвижения снижена. 

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
