### ISSUE TITLE
[Задание] ID 9294 - Исцеление озера

### ISSUE THREAD

**Issue by Kootiki** [VirginTeam/LegionCore#289]
Ссылки и комментарии:

http://ru.wowhead.com/quest=9294

Что работает не так?

Используя квестовый итем, в нужном месте, не выполняется задание. Пишет: "Требуется: Облученный кристалл из серебристого озера"

Как должно работать?

Подходишь к кристаллу, юзаешь итем и задание выполняется.  
https://www.youtube.com/watch?v=a2Bm5wOS994&feature=youtu.be

Шаги для воспроизведения ошибки:

1. Подходим к кристаллу.
2. Используем нейтрализующее вещество.
3. Квест не выполняется.

**Comment by Ewropa** [comment]
https://github.com/VirginTeam/LegionCore/issues/101
