### ISSUE TITLE
Брошюра об уроках верховой езды

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#29]
**Описание:**

Не дает задание.

**Что работает не так?**

http://ru.wowhead.com/item=46875 не дает задание.

**Как должно работать?**

Должна давать квест http://ru.wowhead.com/quest=14079 Релог после 20 лвл не помогает.

**Comment by Ewropa** [comment]
От DELbleart27 (512 – 2·6) 2012-01-14 (Обновление 4.3.0) |   |  
Задание недоступно в игре.
