### ISSUE TITLE
[Задание] ID 12641 - Смерть подбирается с высоты

### ISSUE THREAD

**Issue by Relexq** [VirginTeam/LegionCore#298]
**Ссылки и комментарии:**
http://ru.wowhead.com/quest=12641

**Что работает не так?**

У око нету способностей, чтобы засчитало наблюдение, всего их 2
1)http://ru.wowhead.com/spell=51859
2)http://ru.wowhead.com/spell=51904

**Как должно работать?**

Должно активироваться око, и даваться способности

**Шаги для воспроизведения ошибки:**

1. Берем квест
2. Око летит к Алому ордену
3. У нас нет способностей, чтобы закончить кв =(

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
