### ISSUE TITLE
Лишний восклицательный знак

### ISSUE THREAD

**Issue by Sinegosa** [VirginTeam/LegionCore#3]
**Описание:**

Лишний восклицательный знак.

**Что работает не так?**

Баг текстуры, лишний восклицательный знак.

**Как должно работать?**

Должен быть только один восклицательный знак над головой нпс.

https://media.discordapp.net/attachments/405749645160218624/405752358551683072/unknown.png?width=635&height=508

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by gmOverfire** [comment]
Нет бага текстуры.
Включаем ГМ режим и видим НПЦ http://joxi.ru/DmBL6EyswDQv8A

**Comment by Kodekc** [comment]
Триггер не должен давать задание, надо понять от чего триггер и реализовать его правильную работу
