### ISSUE TITLE
[Заклинание] ID 207142 Лавина #2

### ISSUE THREAD

**Issue by Relexq** [VirginTeam/LegionCore#311]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=207142

**Что работает не так?**

Наносит 1 ед. урона, хотя на способности написано 207 ед. 

**Как должно работать?**

Должно наносится больше, чем 1 ед. урона

**Шаги для воспроизведения ошибки:**

1. Берем талант
2. Подбегаем к противнику
3. Плачем от урона 

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmOverfire** [comment]
Дубликат, не зачем отдельный репорт на эту механику.
#310
