### ISSUE TITLE
[Заклинание] ID 207311 Стискивающие тени #2

### ISSUE THREAD

**Issue by Relexq** [VirginTeam/LegionCore#321]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=207311

**Что работает не так?**

Бьет всех сразу, будто они находятся в Смерть и разложение(http://ru.wowhead.com/spell=52212)

**Как должно работать?**

Должно бить одну цель 

**Шаги для воспроизведения ошибки:**

1. Найти кучу противников
2. Нажать Стискивающие тени
3. Смотреть на много циферок 

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmOverfire** [comment]
#320
