### ISSUE TITLE
Дворфийский шпион (quest=8483)

### ISSUE THREAD

**Issue by Anafobia** [VirginTeam/LegionCore#38]
**Описание:**

При разговоре с  npc=15420 ничего не происходит.

**Что работает не так?**

При разговоре с  npc=15420 ничего не происходит.

**Как должно работать?**

npc=15420 должен подниматься наверх, после становится враждебным.

**Шаги для воспроизведения ошибки:**

1. Берем http://ru.wowhead.com/quest=8483
2. Идем разговаривать с  npc=15420

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/12
