### ISSUE TITLE
[Задание] ID 8346 - Неутолимая жажда

### ISSUE THREAD

**Issue by Sinegosa** [VirginTeam/LegionCore#4]
**Описание:**

Задание [[Thirst Unending]](http://www.wowhead.com/quest=8346/thirst-unending) считается выполненным просто от убийства Маназмея. Даже не юзая Волшебный поток.

**Что работает не так?**

Задание [Thirst Unending] считается выполненным просто от атаки Маназмея. Даже не юзая Волшебный поток.

**Как должно работать?**

Нужно ударить моба заклинанием [Волшебный поток](http://ru.wowhead.com/spell=28730).

**Шаги для воспроизведения ошибки:**

1. Берем квест
2. Аггрим моба
3. Бьем любым спелом и кв засчитан.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Sinegosa** [comment]
На тринити кв не работает вообще

**Comment by Kodekc** [comment]
Updated Mana Wyrm (SAI - Priest missing spell)
