### ISSUE TITLE
[Заклинание] ID 203538 - Великое благословение королей

### ISSUE THREAD

**Issue by Relexq** [VirginTeam/LegionCore#412]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=203538

**Что работает не так?**

Слетает после получения урона

**Как должно работать?**

Должна вешаться на час и поглощать урон и не слетать 

**Шаги для воспроизведения ошибки:**

1. Кидаем каску
2. Подходим к мобам и агрим
3. Каски нету

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
