### ISSUE TITLE
[Заклинание] ID 231832 - Клинок гнева

### ISSUE THREAD

**Issue by Relexq** [VirginTeam/LegionCore#413]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=231832

**Что работает не так?**

Не откатывает Клинок Справедливости(http://ru.wowhead.com/spell=184575)

**Как должно работать?**

Ваши автоатаки с некоторой вероятностью мгновенно завершат время восстановления "Клинка Справедливости".

**Шаги для воспроизведения ошибки:**

1. Бьем Клинком справедливости
2. И продолжаем бить автоатакой
3. Кд не слетает

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
