### ISSUE TITLE
[Заклинание] ID 234299 - Кулак правосудия

### ISSUE THREAD

**Issue by Relexq** [VirginTeam/LegionCore#415]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=234299 - ретрик
http://ru.wowhead.com/spell=198054 - Холик и протик

**Что работает не так?**

В ретрике: - не снижает кд молота правосудия(http://ru.wowhead.com/spell=853) на 2.5 сек  за каждую ед. силы света.
В холике и протике: - Не снижает кд молота правосудия на 10сек от применения способности правосудие(http://ru.wowhead.com/spell=20271)

**Как должно работать?**

В ретрике:  За каждую израсходованную единицу энергии Света оставшееся время восстановления "Молота правосудия" сокращается на 2.5 сек.
В холике и протике:  "Правосудие" сокращает оставшееся время восстановления "Молота правосудия" на 10 сек.

**Шаги для воспроизведения ошибки:**

1. Выбираете один из спеков
2. Станите и делаете необходимые условия, что выше
3. Кд не снижается 

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
