### ISSUE TITLE
[Заклинание] ID 184662 - Щит возмездия

### ISSUE THREAD

**Issue by Relexq** [VirginTeam/LegionCore#416]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=184662

Не корректный урон, наносит 1 ед. урона

Фактический результат — тот, который вы наблюдаете 

**Как должно работать?**

Создает барьер из света небес, поглощающий (Attack power * 20) ед. урона в течение 15 sec. Когда он разрушается, весь поглощенный им урон равномерно распределяется между всеми противниками в радиусе 8 м в виде урона от светлой магии. 

**Шаги для воспроизведения ошибки:**

1. Вешаем на себя
2. Находим противника
3. Сбивают с 1-го удара и он наносит 1 ед урона

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
