### ISSUE TITLE
[Заклинание] ID 223817 - Божественный замысел

### ISSUE THREAD

**Issue by Relexq** [VirginTeam/LegionCore#417]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=223817

**Что работает не так?**

Прокает от всего, абсолютно, даже от того, что сел на маунта

**Как должно работать?**

При использовании способности, расходующей энергию Света, с вероятностью 20% ваша следующая способность, расходующая энергию Света, не потребует ее затрат на применение.

**Шаги для воспроизведения ошибки:**

1. Беру талант
2. Сажусь на маунта
3. Прок

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлено
