### ISSUE TITLE
[Заклинание] ID 209785 - Пламя справедливости

### ISSUE THREAD

**Issue by Relexq** [VirginTeam/LegionCore#418]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=209785

**Что работает не так?**

Баф остается после траты энергий света

**Как должно работать?**

На применение вашей следующей способности, наносящей урон или восстанавливающей здоровье и расходующей энергию Света, будет потрачено на 1 ед. энергии Света меньше.

После использования вердикта храмовника(http://ru.wowhead.com/spell=85256)или любого другого спела, который требует энергию света баф должен спадать, но остается.

**Шаги для воспроизведения ошибки:**

1. Беру талант
2. Жму УВС и спамлю вердиктом
3. баф остается

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Для исправления бага нужно править каждый спелл в отдельности, конкретно для вердикта исправлено, будет также применяться и для других постепенно
