### ISSUE TITLE
[Задание] ID 27726 - Воззвание к героям: гора Хиджал!

### ISSUE THREAD

**Issue by Relexq** [VirginTeam/LegionCore#438]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=27726

**Что работает не так?**

Нет диалога с http://ru.wowhead.com/npc=15187

**Как должно работать?**

После взятия кв, должен появится диалог с http://ru.wowhead.com/npc=15187, но его нету и получается нельзя юзнуть портал

**Шаги для воспроизведения ошибки:**

1. взять кв
2. полететь к Кенарийская посланница Нефритовая Луна
3. Лететь самому, диалога нету ._.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Исправлено. Изменения будут применены в ближайшем обновлении
