### ISSUE TITLE
[Задание] ID 26782/26783 - Сокровища клана Мош'Огг

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#46]
**Описание:**

Квест-дубликат http://www.wowhead.com/quest=26783/the-moshogg-bounty

**Что работает не так?**

Квест-дубликат, можно взять и выполнить оба.

**Как должно работать?**

Квест должен быть 1

**Comment by Kodekc** [comment]
Updated Wulfred Harrys (queststarter/questender).
