### ISSUE TITLE
[Задание] ID 26740 - Горшок Кразека

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#48]
**Описание:**

Не отображает на карте место сдачи квеста http://ru.wowhead.com/quest=26740

**Что работает не так?**

Нет отбражения на карте, где сдавать квест

**Как должно работать?**

Должно отображать на карте, где сдавать квест http://ru.wowhead.com/quest=26740#map

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/63
