### ISSUE TITLE
[Задание] ID 8330/37443 - Вещи Соланиана

### ISSUE THREAD

**Issue by Sinegosa** [VirginTeam/LegionCore#5]
**Описание:**

Задание  [[Solanian's Belongings]](http://www.wowhead.com/quest=8330/solanians-belongings), в книге не отображается, что необходимые предметы уже есть, хотя они уже лежат в сумке.

**Что работает не так?**

В книге заданий не отображается, что необходимые предметы уже есть, хотя они уже лежат в сумке. Возможно не отображается из-за того, что это один из квестов-дубликатов. И если бы у меня было по 2 предмета каждого вида, то засчиталось бы. (Несмотря на то, что не показывает. что предметы есть кв можно сдать имея предметы в сумке)
https://media.discordapp.net/attachments/405749645160218624/405755127597760512/unknown.png?width=635&height=508

**Как должно работать?**

Должно отображать, что предмет есть если он есть в сумке.

**Шаги для воспроизведения ошибки:**

1. Берем квест
2. Находим и берем любую вещь из требуемых

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Sinegosa** [comment]
На тринити работает

**Comment by Kodekc** [comment]
Updated Well Watcher Solanian (queststarter/questender).
