### ISSUE TITLE
[NPC] ID 44082/44099 - Бронвин Зарубай и Даск "Пузырь" Гоблопшик 

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#50]
**Описание:**

Все указанные ниже квесты имеют дубликаты, которые так же можно взять и сдать одновременно. Данные квесты должны быть в 1 экземпляре

1) Даск "Пузырь" Гоблопшик http://ru.wowhead.com/quest=26825 Данный квест берется в 2м экземпляре как у http://ru.wowhead.com/npc=44082 , так и у http://ru.wowhead.com/npc=44099 При взятии у любого из этих НПЦ у второго квесты исчезают. Квест должен браться только у http://ru.wowhead.com/npc=44082 Сдать можно 2 кв.

**Comment by Kodekc** [comment]
Updated Bronwyn Hewstrike and Dask "The Flask" Gobfizzle (queststarter/questender).
