### ISSUE TITLE
[NPC] ID 26879 - Томас Ривервелл <Укротитель грифонов>

### ISSUE THREAD

**Issue by Anineta** [VirginTeam/LegionCore#502]
**Ссылки и комментарии:**

http://ru.wowhead.com/npc=26879

**Что работает не так?**

Не хочет предоставлять полеты. Окно диалога пустое. 

**Как должно работать?**

Должен давать возможно полетать на грифоне.

**Шаги для воспроизведения ошибки:**

1. Находим НИПа
2. Пытаемся улететь
3. Ничего не выходит

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Исправлено. Изменения будут применены в ближайшем обновлении
