### ISSUE TITLE
[Заклинание] ID 164545 - Солнечное могущество

### ISSUE THREAD

**Issue by Relexq** [VirginTeam/LegionCore#531]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=164545
сова

**Что работает не так?**

Не слетает баф, после использования Гнева(http://ru.wowhead.com/spell=5176)

**Как должно работать?**

Должен слетать 1-н стак бафа за использование Гнева, но у нас остается

**Шаги для воспроизведения ошибки:**

1. делаем друида
2. получаем солнечное могущество
3. спамим апнутым гневом постоянно

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/LegionCore/issues/531
