### ISSUE TITLE
[Заклинание] ID 783 - Походный облик

### ISSUE THREAD

**Issue by Relexq** [VirginTeam/LegionCore#533]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=783
сова

**Что работает не так?**

Не превращает в форму, остаемся в начальной при использований

**Как должно работать?**

Вы принимаете походный облик, соответствующий вашему местоположению. Скорость передвижения по земле, воде или воздуху повышается; кроме того, походный облик защищает вас от эффектов превращения.

**Шаги для воспроизведения ошибки:**

1. Качаю друида
2. Юзаю облик
3. ничего не произошло

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/LegionCore/issues/227
