### ISSUE TITLE
[NPC] ID 5159 - Дерил Рикнуссун 

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#54]
**Ссылки**
http://ru.wowhead.com/npc=5159
http://ru.wowhead.com/quest=29356
http://ru.wowhead.com/quest=29351
http://ru.wowhead.com/quest=29352
http://ru.wowhead.com/quest=29353
http://ru.wowhead.com/quest=29355
http://ru.wowhead.com/quest=6612

 **Описание:**

Ежедневные кулинарные квесты доступны без взятой профы и сразу все.

**Что работает не так?**
 НПЦ Дерил Рикнуссун <Учитель кулинарии>
Все квесты доступны одновременно. 

![wowscrnshot_012718_012047](https://user-images.githubusercontent.com/29457913/35463236-1cced9b8-0309-11e8-84e5-f7fb028f6b54.jpg)

**Как должно работать?**

Ежедневные квесты должны даваться при наличии Кулинарии (1) персам выше 10 лвл по одному.

**Ядро**
28.01.2018 Test Build - Trinity

**Comment by Kodekc** [comment]
Исправлено. Будет применены в ближайшем обновлении
