### ISSUE TITLE
[Группа NPC] - Неверный набор товаров и цен у NPC в Палате Героев

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#55]
**Ссылки**
1) http://ru.wowhead.com/npc=12805
2) http://ru.wowhead.com/npc=12783
3) http://ru.wowhead.com/npc=12785
4) http://ru.wowhead.com/npc=69975
5) http://ru.wowhead.com/npc=40607
6) http://ru.wowhead.com/npc=12781
7) http://ru.wowhead.com/npc=52030
8) http://ru.wowhead.com/npc=52029

**Описание:**

1 На офф.сайте (Дракономор) на этом месте ее нет вообще. В других не нашла.
2 - 6 Не выставлены цены
7 - 8 Не верен набор товаров по сравнению с оффом. Не выставлены цены.

**Ядро**
28.01.2018 Test Build - Trinity

**Comment by Kodekc** [comment]
Removed Officer Areyn (deleted from the game)
Updated Lieutenant Karter (npc vendor)
Updated Sergeant Major Clate (npc vendor)
Updated Captain Dirgehammer (npc vendor)
Updated Knight-Lieutenant T'Maire Sydes  (npc vendor)
Updated Master Sergeant Biggins (npc vendor)
Updated Liliana Emberfrost (npc vendor)
Updated Edlan Halsing (npc vendor)
Necrolord Sipe (npc vendor)
Lieutenant Tristia (npc vendor)
