### ISSUE TITLE
квест quest=13613

### ISSUE THREAD

**Issue by FORDeX** [VirginTeam/LegionCore#579]
Не лечит выбраных в таргет npc http://ru.wowhead.com/quest=13613

20 - 24

**Comment by gmKroshka** [comment]
Пожалуйста, прочитайте базовую информацию о стандартах для заголовков при создании репорта:

При создании заголовка пишите: [Категория] ID № - Название
Примеры:

Если это касается конкретного существа: [NPC] ID 34320 - Равазаврик

Если это касается подземелья и конкретного босса: [Подземелье] Каражан (ID 18168 Ведьма)

Если это касается заклинания: [Заклинание] ID 48666 - Расправа

Если это касается группы заклинаний, заданий или в целом содержит более одного репорта в себе, то есть является комплексным репортом: [Группа заклинаний] Призыв питомца

Все категории пишите на русском языке, за исключением NPC, эта категория единственная на английском языке.
Если у категории нет ID, к примеру, вы его не знаете или его нет, можно не указывать это
Не переживайте, если боитесь ошибиться при создании заголовка, его можно отредактировать в любое время или это могут сделать сотрудники команды поддержки багтрекера.
Очень содержательное видео по основам создания репортов: Перейти на Youtube

**Comment by FORDeX** [comment]
я так загребусь всё расписывать честно
