### ISSUE TITLE
[Группа NPC] - Неверный набор товаров и цен у NPC в Оргриммаре

### ISSUE THREAD

**Issue by Anafobia** [VirginTeam/LegionCore#58]
**Описание:**

В http://ru.wowhead.com/npc=52036 фамильные предметы не имеют цены.
http://ru.wowhead.com/npc=52030  фамильные предметы не имеют цены.

**Что работает не так?**

В http://ru.wowhead.com/npc=52036 фамильные предметы не имеют цены.
http://ru.wowhead.com/npc=52030  фамильные предметы не имеют цены.

**Как должно работать?**
Должно продаваться за http://ru.wowhead.com/item=137642. Ниже перечислены предметы и цена:

http://ru.wowhead.com/item=122338 - 12 шт.
http://ru.wowhead.com/item=122339 - 14 шт.
http://ru.wowhead.com/item=122364&bonus=0 - 10 шт.
http://ru.wowhead.com/item=122365&bonus=0 - 10 шт.
http://ru.wowhead.com/item=122366&bonus=0 - 10 шт.
http://ru.wowhead.com/item=122367&bonus=0 - 10 шт.
http://ru.wowhead.com/item=122368&bonus=0 - 10 шт.
http://ru.wowhead.com/item=122369&bonus=0 - 10 шт.
http://ru.wowhead.com/item=122530&bonus=0 - 4 шт.
http://ru.wowhead.com/item=122370&bonus=0 - 4 шт.
http://ru.wowhead.com/item=122372&bonus=0 - 8 шт.
http://ru.wowhead.com/item=122373&bonus=0 - 8 шт.
http://ru.wowhead.com/item=122374&bonus=0 - 8 шт.
http://ru.wowhead.com/item=122375&bonus=0 - 8 шт.
http://ru.wowhead.com/item=122377&bonus=0 - 8 шт.
http://ru.wowhead.com/item=122378&bonus=0 - 8 шт.

**Шаги для воспроизведения ошибки:**

1. Подходим к npc=52036 / npc=52030
2. Покупаем предмет.

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/55

**Comment by Kodekc** [comment]
Обновил всех торговцев в Зале Легенд. Изменения будут применены в ближайшем обновлении
