### ISSUE TITLE
Оружие дальнего боя

### ISSUE THREAD

**Issue by Hlebovoz** [VirginTeam/LegionCore#586]
**Ссылки и комментарии:**

https://imgur.com/a/XhxAn

**Что работает не так?**

Нельзя стрелять из оружия дальнего боя и юзать скиллы за ханта.

**Как должно работать?**

Оружие дальнего боя должно стрелять и есть возможность использовать способности охотника.

**Шаги для воспроизведения ошибки:**

1. Создать охотника
2. Зайти в мир
3. Огорчится т.к нельзя стрелять :(

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Проблема не воспроизводится, создал гоблина охотника - и выстрелы и способности работают

**Comment by Hlebovoz** [comment]
Я понял как воспроизвести этот баг: 
1. Нужно взять квест http://ru.wowhead.com/quest=14153 (Банкет).
2. Потом его отменить
3. Нельзя стрелять
