### ISSUE TITLE
[Заклинание] ID 184092 - Свет защитника

### ISSUE THREAD

**Issue by alaevv** [VirginTeam/LegionCore#591]
**Ссылки и комментарии:**
http://ru.wowhead.com/spell=184092

**Что работает не так?**
Восстанавливает 30 единиц здоровья

**Как должно работать?**
Должен восстанавливать 30% от недостающего здоровья

**Шаги для воспроизведения ошибки:**

1. При любом уроне здоровья
2. Применяем Свет защитника
3. На индикаторе здоровья видим, что восстановилось 30 единиц здоровья, а не 30% недостающего здоровья.

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by ForesterDev** [comment]
Исправлно

**Comment by alaevv** [comment]
Я сейчас проверил, восстанавливает 30 единиц здоровья а не 30% недостающего. 
Персонаж Aval паладин 91-уровня.

**Comment by gmKroshka** [comment]
Обновление ещё не установлено

**Comment by alaevv** [comment]
Свет защитника и Длань защитника работают правильно.
