### ISSUE TITLE
[Задание] ID 27635 - Санобработка

### ISSUE THREAD

**Issue by Arxsochi** [VirginTeam/LegionCore#592]
**Ссылки и комментарии:**

Квест http://ru.wowhead.com/quest=27635
NPC http://ru.wowhead.com/npc=46185/500

**Что работает не так?**
Не начинает процедуру очищения

Фактический результат — тот, который вы наблюдаете 
При использовании NPC персонаж зависает в его лапах и ничего не происходит

**Как должно работать?**
Использовать NPC и начнется процедура очищения

**Шаги для воспроизведения ошибки:**

1. Берем квест
2. Используем NPC
3. Идет процедура очищения

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/LegionCore/issues/202
