### ISSUE TITLE
[Задание] ID 26205 - Работа для робота

### ISSUE THREAD

**Issue by Arxsochi** [VirginTeam/LegionCore#593]
**Ссылки и комментарии:**

Квест-http://ru.wowhead.com/quest=26205

**Что работает не так?**
Не засчитывает очищение ядовитых гейзеров
Фактический результат — тот, который вы наблюдаете 
Ядовитые гейзеры отсутствуют

**Как должно работать?**

Очищающий робот должен подбегать к гейзерам и очищать их

**Шаги для воспроизведения ошибки:**

1. Берем квест
2. Бежим к ядовитым гейзерам
3. Робот их очищает

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/LegionCore/issues/209
