### ISSUE TITLE
[Заклинание] ID 116694 - Излияние

### ISSUE THREAD

**Issue by Arxsochi** [VirginTeam/LegionCore#594]
**Ссылки и комментарии:**

Заклинание http://ru.wowhead.com/spell=116694

**Что работает не так?**
Не хилит цель
Фактический результат — тот, который вы наблюдаете 
При выделении цели не хилит ее так же при нон таргете не хилит себя.
**Как должно работать?**
Быстрое и эффективное заклинание, восполняющее (250% of Attack power) ед. здоровья цели.

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/LegionCore/issues/204
