### ISSUE TITLE
[Задание] ID 313 - Вести наблюдение издалека

### ISSUE THREAD

**Issue by Arxsochi** [VirginTeam/LegionCore#595]
**Ссылки и комментарии:**

http://ru.wowhead.com/quest=313 

**Что работает не так?**

Не передается распоряжение капитана при разговоре с пехотинцами.

**Как должно работать?**

При разговоре с пехотинцами должно передаваться распоряжение капиана

**Шаги для воспроизведения ошибки:**

1. Берем квест
2. Поочередно разговариваем с квестовыми НПС
3. Распоряжение капитана передается квестовым НПС

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/LegionCore/issues/211
