### ISSUE TITLE
[Заклинание] ID 196607 - Глаз тигра

### ISSUE THREAD

**Issue by Arxsochi** [VirginTeam/LegionCore#597]
**Ссылки и комментарии:**

http://ru.wowhead.com/spell=196607 

**Что работает не так?**
Не хилит монаха

Фактический результат — Здоровье цели отнимается но у монаха не прибавляется

**Как должно работать?**
"Лапа тигра" также накладывает эффект "Глаз тигра", в течение 8 sec. наносящий противнику (172% of Attack power) ед. урона от сил природы, и восстанавливающий монаху (172% of Attack power) ед. здоровья.

Ожидаемый результат — Хилит монаха

**Шаги для воспроизведения ошибки:**

1. Выбор таланта
2. Нанесение урона
3. Восстанавливает здоровье монаху

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/LegionCore/issues/232
