### ISSUE TITLE
[Задание] ID 14091 - Дурной знак

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#60]
**Описание:**

Невозможно сдать квест.

**Что работает не так?**

Над НПЦ ID 34913, которому надо сдать квест, нет занака вопроса.

**Как должно работать?**

Ожидаемый результат — сдать квест)

**Comment by Kodekc** [comment]
Updated Prince Liam Greymane (queststarter/questender).

**Comment by Ewropa** [comment]
там 2 принца:
 - в фазе 1 принц http://ru.wowhead.com/npc=34850
 - в фазу 2 принц http://ru.wowhead.com/npc=34913
а вообще на сервере нарушено фазирование у воргенов, это общая проблема trinity
при принятия задания, персонаж должен переходить в фазу 2, чего не происходит, вот поэтому и не можете сдать задание, хотя в Гм режиме все прекрасно робит)
