### ISSUE TITLE
[Задача] Задания не отображаются на карте

### ISSUE THREAD

**Issue by Kodekc** [VirginTeam/LegionCore#63]
**Описание:**

Вся группа заданий, когда нужно с кем-то поговорить и это является целью задания, не отображает цель задания на игровой карте

**Что работает не так?**

Задание взято, цели задания на карте нет

**Как должно работать?**

Цель должна быть на карте для удобства орентирования

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять заголовки для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by ForesterDev** [comment]
Исправлено
