### ISSUE TITLE
[Задание] ID 8338 - Оскверненный магический осколок

### ISSUE THREAD

**Issue by Sinegosa** [VirginTeam/LegionCore#7]
**Описание:**

Задание [[Tainted Arcane Sliver]](http://www.wowhead.com/quest=8338/tainted-arcane-sliver) светится будто не сделанное, но его нужно просто сдать после того, как взял. 

**Что работает не так?**

Задание [[Tainted Arcane Sliver]](http://www.wowhead.com/quest=8338/tainted-arcane-sliver) светится будто не сделанное, но его нужно просто сдать после того, как взял.

**Как должно работать?**

При получении данного кв, на карте сразу должен гореть знак вопроса где сдать. А сдавать его нужно у [него](http://ru.wowhead.com/npc=15297).

**Шаги для воспроизведения ошибки:**

1. Выбиваем из моба [Нечистый чародейский призрак](http://ru.wowhead.com/npc=15298) - [Оскверненный магический осколок](http://ru.wowhead.com/item=20483)
2. Осколок дает кв [[Tainted Arcane Sliver]](http://www.wowhead.com/quest=8338/tainted-arcane-sliver)
3. Смотрим на карту:
https://cdn.discordapp.com/attachments/405749645160218624/405759521852489738/unknown.png

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Sinegosa** [comment]
актуально на тринити

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/63
