### ISSUE TITLE
[Задание] id 24755 - Превосходя ожидания

### ISSUE THREAD

**Issue by gmOverfire** [VirginTeam/LegionCore#74]
**Ссылки и комментарии:**

Квесты мага
http://ru.wowhead.com/quest=24754
http://ru.wowhead.com/quest=24752
http://ru.wowhead.com/quest=24755

**Что работает не так?**

После 24754 не выдается 24755. Нужно выполнить еще один квест 24752, который опять таки не выдается, но даже если и будет выдан - выполнить его нельзя, т.к требуемый скилл изучается на 5 уровне. 

**Как должно работать?**

После 24754 должен выдаваться 24755, на офе более не выполняется 24752.
http://joxi.ru/DmBL6EyswD7kEA

**Текущее обновление ядра:**

01/02/18

[//]: # (** Всё, что выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для удобства оформления репортов. **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте основную информацию, как оформлять репорты и заголовки. **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта и/или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)

**Comment by Kodekc** [comment]
Updated Proving Pit (Individual quest template)
