### ISSUE TITLE
[Задание] ID 9705 - Возвращение свертка

### ISSUE THREAD

**Issue by Sinegosa** [VirginTeam/LegionCore#8]
**Описание:**

[[Package Recovery]](http://www.wowhead.com/quest=9705/package-recovery) не отображает на карте где его сдать.

**Что работает не так?**

Карта не отображает где сдать кв  [[Package Recovery]](http://www.wowhead.com/quest=9705/package-recovery)

https://cdn.discordapp.com/attachments/405749645160218624/405760812427378698/unknown.png

**Как должно работать?**

Должно отображать - http://ru.wowhead.com/quest=9705/package-recovery#map

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Sinegosa** [comment]
актуально на тринити. Все эти кв начинают показывать точку сдачи после релога

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/63
