### ISSUE TITLE
[Задание] ID 26652 - Нить из призрачных волос

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#80]
**Что работает не так?**

Не отображает на карте, где сдается квест.
Тринити.

**Как должно работать?**

Должно отображаться на карте, где сдавать квест (Сдается НПЦ Слепая Мэри http://ru.wowhead.com/npc=302, на карте http://ru.wowhead.com/quest=26652#map )

Так же при завершении квеста у НПЦ нет текста сдачи квеста.

Текст:

Что это? Гребень? Какая прелесть! И он спокойно скользит по моим волосам, хотя они давно сбились в ужасный слипшийся колтун.

Ах, мне бы в зеркало посмотреться...

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/63
