### ISSUE TITLE
[Лут] ID 60401- Нежная кабанина

### ISSUE THREAD

**Issue by Senatyan** [VirginTeam/LegionCore#82]
http://ru.wowhead.com/item=60401

Добавьте ссылки с wowhead.com или db.logon3.com на проблемные задания, NPC, заклинания и т.д. 

**Что работает не так?**

Чтобы сделать кв http://ru.wowhead.com/quest=86 нужно получить 4 кусочка http://ru.wowhead.com/item=60401, а чтобы их выбить мне пришлось убить  30+ http://ru.wowhead.com/npc=113, 26 точно судя по сумке в которой валяется http://ru.wowhead.com/item=769
То есть http://ru.wowhead.com/item=769 работает правильно шанс дропа 23% падает почти с каждого http://ru.wowhead.com/npc=113
Тут шанс дропа 21% http://ru.wowhead.com/item=60401 
Это просто пытка будет для лоу лвл
https://www.youtube.com/watch?v=gs_M3A3QCZA&feature=youtu.be

**Как должно работать?**
https://www.youtube.com/watch?v=jbJJim3bF5w
https://www.youtube.com/watch?v=OUPV-KLvaj8
https://www.youtube.com/watch?v=NmpU3ijE9jE&feature=youtu.be
http://ru.wowhead.com/item=60401  должно падать почти с каждого кабана

**Шаги для воспроизведения ошибки:**

1. Убивать кабанов
2. Очень много убивать включая конкурентов

03.02.2018

**Comment by Kodekc** [comment]
Судя по базе, шанс дропа соответствует wowhead
