### ISSUE TITLE
[Задание] ID 26654 - Гребень для Евы

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#86]
**Что работает не так?**

Не отображает на карте, где сдается квест.

**Как должно работать?**

Должно отображаться на карте, где сдавать квест. http://ru.wowhead.com/quest=26654#map

**Текущее обновление ядра:**

Тринити

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/63
