### ISSUE TITLE
[Задание] ID 334 - Посылка для Турмана

### ISSUE THREAD

**Issue by Senatyan** [VirginTeam/LegionCore#88]
Что работает не так?

Не отображает на карте, где сдается квест. 

Как должно работать?

Должно отображаться на карте, где сдавать квест. http://ru.wowhead.com/quest=334#map

Текущее обновление ядра:
Тринити

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/63
