### ISSUE TITLE
[Задание] ID 29067 - Мастер зелий

### ISSUE THREAD

**Issue by Senatyan** [VirginTeam/LegionCore#90]
Ссылки и комментарии

http://ru.wowhead.com/quest=29067

Что работает не так?

Можно взять кв вообще не имея ни одну профу

Как должно работать?

Задания доступны после получения навыка 475.

03.02.2018 Test Build - Trinity

**Comment by Ewropa** [comment]
необходимо добавить это
RequiredSkillPoints = 475

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/175
