### ISSUE TITLE
[Задание] ID 29481 - Мастер эликсиров

### ISSUE THREAD

**Issue by Senatyan** [VirginTeam/LegionCore#91]
Ссылки и комментарии

http://ru.wowhead.com/quest=29481

Что работает не так?

Можно взять кв вообще не имея ни одну профу

Как должно работать?

Задания доступны после получения навыка 475.

03.02.2018 Test Build - Trinity

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/LegionCore/issues/175
