### ISSUE TITLE
[НПЦ] ID 6294 - Кром Крепкорук <Смотритель наследуемых предметов>

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/LegionCore#95]
**Ссылки и комментарии:**

http://ru.wowhead.com/npc=6294

**Что работает не так?**

Невозможно купить фамильные вещи - нет диалога.

**Как должно работать?**

Должен продавать наследуемые вещи и улучшения для них.

**Текущее обновление ядра:**

28.01.2018 Test Build - Trinity

**Comment by Senatyan** [comment]
Вроде дубль

**Comment by Senatyan** [comment]
https://github.com/VirginTeam/LegionCore/issues/66
